<a href="https://colab.research.google.com/github/jasonkjw/daily_coding_commit/blob/main/hon05_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
wine = pd.read_csv('https://bit.ly/wine_csv_data')
data = wine[['alcohol','sugar','pH']]
target = wine['class']

from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target = train_test_split(data, target, test_size=0.2, random_state=42)
sub_input, val_input, sub_target, val_target = train_test_split(train_input, train_target, test_size=0.2, random_state=42)

print(sub_input.shape, val_input.shape)

(4157, 3) (1040, 3)


In [2]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(random_state=42)
dt.fit(sub_input, sub_target)
print(dt.score(sub_input, sub_target))
print(dt.score(val_input, val_target))

0.9971133028626413
0.864423076923077


In [3]:
from sklearn.model_selection import cross_validate
score = cross_validate(dt, train_input, train_target)
print(score)

{'fit_time': array([0.0174129 , 0.01493669, 0.02361012, 0.01479816, 0.01446867]), 'score_time': array([0.00388908, 0.00355816, 0.00389171, 0.00960183, 0.00365543]), 'test_score': array([0.86923077, 0.84615385, 0.87680462, 0.84889317, 0.83541867])}


In [4]:
import numpy as np
print(np.mean(score['test_score']))

0.855300214703487


In [5]:
from sklearn.model_selection import StratifiedKFold
score = cross_validate(dt, train_input, train_target, cv=StratifiedKFold())
print(np.mean(score['test_score']))

0.855300214703487


In [6]:
splitter = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_validate(dt, train_input, train_target, cv=splitter)
print(np.mean(scores['test_score']))

0.8574181117533719


In [7]:
from sklearn.model_selection import GridSearchCV
params = {'min_impurity_decrease': [0.0001, 0.0002, 0.0003, 0.0004, 0.0004]}
gs = GridSearchCV(DecisionTreeClassifier(random_state=42), params, n_jobs=-1)
gs.fit(train_input, train_target)
dt = gs.best_estimator_
print(dt.score(train_input, train_target))

0.9615162593804117


In [8]:
print(gs.best_params_)

{'min_impurity_decrease': 0.0001}


In [9]:
print(gs.cv_results_['mean_test_score'])

[0.86819297 0.86453617 0.86492226 0.86780891 0.86780891]


In [10]:
print(gs.cv_results_['params'][gs.best_index_])

{'min_impurity_decrease': 0.0001}


In [11]:
params = {'min_impurity_decrease': np.arange(0.0001, 0.001, 0.0001), 'max_depth' : range(5,20,1), 'min_samples_split': range(2,100,10)}

In [12]:
gs = GridSearchCV(DecisionTreeClassifier(random_state=42), params, n_jobs=-1)
gs.fit(train_input, train_target)
print(gs.best_params_)

{'max_depth': 14, 'min_impurity_decrease': np.float64(0.0004), 'min_samples_split': 12}


In [13]:
print(np.max(gs.cv_results_['mean_test_score']))

0.8683865773302731


In [14]:
from scipy.stats import uniform, randint
rgen = randint(0, 10)
rgen.rvs(10)

array([1, 3, 0, 7, 8, 9, 1, 8, 3, 2])

In [15]:
np.unique(rgen.rvs(1000), return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 99,  98, 121,  89, 129,  92,  93, 101, 100,  78]))

In [ ]:
ugen = uniform(0,1)
ugen.rvs(10)
